#pragma once

/* nes controller gpio  */
#define HW_CONTROLLER_GPIO
#define HW_CONTROLLER_GPIO_UP 41
#define HW_CONTROLLER_GPIO_DOWN 39
#define HW_CONTROLLER_GPIO_LEFT 38
#define HW_CONTROLLER_GPIO_RIGHT 40
#define HW_CONTROLLER_GPIO_SELECT 9
#define HW_CONTROLLER_GPIO_START 0
#define HW_CONTROLLER_GPIO_A 7
#define HW_CONTROLLER_GPIO_B 6
#define HW_CONTROLLER_GPIO_X -1
#define HW_CONTROLLER_GPIO_Y -1